services:
  db:
    # If you really want to use MySQL, uncomment the following line
    image: mysql:8.0.27
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - ./db/mysql/:/var/lib/mysql:rw
    restart: always
    expose:
      - 3306
    env_file:
      - .env.local
  wordpress:
    image: wordpress:latest
    volumes:
      - ./src/wordpress/wp-content/themes/dsbd/:/var/www/html/wp-content/themes/dsbd:rw
      - ./src/wordpress/wp-content/plugins/:/var/www/html/wp-content/plugins:rw
      - ./src/wordpress:/var/www/html:rw
    ports:
      - 80:80
    restart: always
    env_file:
      - .env.local
    depends_on:
      - db
    user: "1000:1000"
  wpcli:
    image: wordpress:cli
    command: tail -f /dev/null
    environment:
      - WP_CLI_PACKAGES_DIR=/var/www/html/.wp-cli
    volumes:
      - ./src:/src/:rw
      - ./src/wordpress:/var/www/html:rw
      - ./src/.wp-cli:/.wp-cli:rw
    user: "1000:1000"
