services:
  db:
    # If you really want to use MySQL, uncomment the following line
    image: mysql:8.0.27
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - sql_data:/var/lib/mysql
    restart: always
    expose:
      - 3306
    env_file:
      - .env.local
    user: "1000:1000"
  wordpress:
    image: wordpress:latest
    volumes:
      - ./src/wp-content/themes/dsbd/:/var/www/html/wp-content/themes/dsbd:rw
      - ./src/wp-content/plugins/:/var/www/html/wp-content/plugins:rw
      - ./src:/var/www/html:rw
    ports:
      - 80:80
    restart: always
    env_file:
      - .env.local
    depends_on:
      - db
  wpcli:
    image: wordpress:cli
    command: tail -f /dev/null
    environment:
      - WP_CLI_PACKAGES_DIR=/var/www/html/.wp-cli
    volumes:
      - ./src/:/var/www/html:rw
    user: "1000:1000"
volumes:
  sql_data:
