name: Deploying Wordpress Site
on:
  push:
    branches:
      - main
jobs:
  Deploy-To-Wordpress:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
      - uses: up9cloud/action-rsync@master
        env:
          HOST: ${{vars.SSH_SERVER_URL}}
          PASSWORD: ${{secrets.SSH_SERVER_PASSWORD}}
          TARGET: .
          SOURCE: src/
          USER: ${{secrets.SSH_SERVER_USER}}
